version: "3.9"

services:
  influxdb:
    image: influxdb:2.7
    container_name: puregold-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      INFLUXD_CONFIG_PATH: /etc/influxdb2/config.toml
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
      - ./config.toml:/etc/influxdb2/config.toml:ro
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  influxdb-data:
  influxdb-config:
