name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  UV_FROZEN: "true"

jobs:
  smoke:
    name: macOS smoke tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-14]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "${HOME}/.local/bin" >> "$GITHUB_PATH"

      - name: Sync dependencies
        run: uv sync --frozen

      - name: Lint
        run: uv run ruff check .

      - name: Smoke test imports
        run: uv run python -c "import polars, pyarrow, influxdb_client"
